//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFilesAdminStudio.CoreModule.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MFilesAdminStudio.CoreModule.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/gnsso/mfiles-vbscript-explorer.
        /// </summary>
        public static string App_GithubAppPageUrl {
            get {
                return ResourceManager.GetString("App_GithubAppPageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/gnsso/mfiles-vbscript-explorer/issues.
        /// </summary>
        public static string App_GoToAppSSSUrl {
            get {
                return ResourceManager.GetString("App_GoToAppSSSUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 550.
        /// </summary>
        public static string App_InitialHeight {
            get {
                return ResourceManager.GetString("App_InitialHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 330.
        /// </summary>
        public static string App_InitialWidth {
            get {
                return ResourceManager.GetString("App_InitialWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 600.
        /// </summary>
        public static string App_MainMinHeight {
            get {
                return ResourceManager.GetString("App_MainMinHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 960.
        /// </summary>
        public static string App_MainMinWidth {
            get {
                return ResourceManager.GetString("App_MainMinWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App.
        /// </summary>
        public static string App_ModuleName {
            get {
                return ResourceManager.GetString("App_ModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppHolder.
        /// </summary>
        public static string App_RegionHolderName {
            get {
                return ResourceManager.GetString("App_RegionHolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core.
        /// </summary>
        public static string Core_ModuleName {
            get {
                return ResourceManager.GetString("Core_ModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mechsoft.
        /// </summary>
        public static string Global_CompanyNameForFileSystem {
            get {
                return ResourceManager.GetString("Global_CompanyNameForFileSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app.db.
        /// </summary>
        public static string Global_DefaultDBName {
            get {
                return ResourceManager.GetString("Global_DefaultDBName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vbscript.xshd.
        /// </summary>
        public static string Global_HighlightingDefFileName {
            get {
                return ResourceManager.GetString("Global_HighlightingDefFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M-Files VB Script Explorer.
        /// </summary>
        public static string Global_LongTitle {
            get {
                return ResourceManager.GetString("Global_LongTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigated from module {0:moduleName}, {1:paramsDescription}.
        /// </summary>
        public static string Global_Message_NavigatedFromModule {
            get {
                return ResourceManager.GetString("Global_Message_NavigatedFromModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigated to module {0:moduleName}, {1:paramsDescription}.
        /// </summary>
        public static string Global_Message_NavigatedToModule {
            get {
                return ResourceManager.GetString("Global_Message_NavigatedToModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NavTransition.
        /// </summary>
        public static string Global_NavTransitionModuleName {
            get {
                return ResourceManager.GetString("Global_NavTransitionModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to payload.
        /// </summary>
        public static string Global_NavTransitionPayloadKey {
            get {
                return ResourceManager.GetString("Global_NavTransitionPayloadKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nlog.xml.
        /// </summary>
        public static string Global_NLogConfigFilePath {
            get {
                return ResourceManager.GetString("Global_NLogConfigFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M-Files VB Script Explorer.
        /// </summary>
        public static string Global_ProductNameForFileSystem {
            get {
                return ResourceManager.GetString("Global_ProductNameForFileSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M-Files VB Script Explorer.
        /// </summary>
        public static string Global_ShortTitle {
            get {
                return ResourceManager.GetString("Global_ShortTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login_LoginCommandText {
            get {
                return ResourceManager.GetString("Login_LoginCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login_ModuleName {
            get {
                return ResourceManager.GetString("Login_ModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Login_PasswordBoxHint {
            get {
                return ResourceManager.GetString("Login_PasswordBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginHolder.
        /// </summary>
        public static string Login_RegionHolderName {
            get {
                return ResourceManager.GetString("Login_RegionHolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login_Server.
        /// </summary>
        public static string Login_Server_ModuleName {
            get {
                return ResourceManager.GetString("Login_Server_ModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Login_UsernameBoxHint {
            get {
                return ResourceManager.GetString("Login_UsernameBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login_Vault.
        /// </summary>
        public static string Login_Vault_ModuleName {
            get {
                return ResourceManager.GetString("Login_Vault_ModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string Main_ModuleName {
            get {
                return ResourceManager.GetString("Main_ModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MainHolder.
        /// </summary>
        public static string Main_RegionHolderName {
            get {
                return ResourceManager.GetString("Main_RegionHolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rootDialog.
        /// </summary>
        public static string Main_RootDialogIdentifier {
            get {
                return ResourceManager.GetString("Main_RootDialogIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VBScriptExplorer.
        /// </summary>
        public static string VBScriptExplorer_ModuleName {
            get {
                return ResourceManager.GetString("VBScriptExplorer_ModuleName", resourceCulture);
            }
        }
    }
}
